"use client";

import { motion } from "motion/react";
import { FileText, ShieldAlert, LineChart, Users, Calendar, ClipboardList } from "lucide-react";

const reportCategories = [
  {
    title: "Executive & Leadership Digests",
    desc: "High-level summary of company progress, major blockers resolved, cross-team milestone completion, and strategic risk alerts.",
    icon: FileText,
    freq: "Weekly / Monthly",
  },
  {
    title: "Security & SOC 2 Audit Logs",
    desc: "Comprehensive tracking of access changes, permission updates, compliance anomalies, and sensitive data access trails.",
    icon: ShieldAlert,
    freq: "Real-time / On-demand",
  },
  {
    title: "Engineering Velocity & Health",
    desc: "Tracks PR review turnaround times, commit frequency, unblocked dependencies, and architectural decision changes.",
    icon: LineChart,
    freq: "Sprint-based",
  },
  {
    title: "Meeting Action Digest",
    desc: "Aggregates key decisions and assigned tasks from all team Zoom/Meet recordings into one scannable document.",
    icon: Calendar,
    freq: "Daily",
  },
  {
    title: "Knowledge Gap Analysis",
    desc: "Identifies single points of failure in documentation, missing onboarding guides, and unmapped technical components.",
    icon: ClipboardList,
    freq: "Monthly",
  },
  {
    title: "Team Workload & Distribution",
    desc: "Monitors allocation across repositories, tickets, and Slack channels to prevent team burnout and bottlenecking.",
    icon: Users,
    freq: "Bi-weekly",
  },
];

export function ReportTypes() {
  return (
    <section className="relative py-24 bg-background/60 border-t border-white/5">
      <div className="mx-auto max-w-6xl px-6">
        <div className="mx-auto max-w-2xl text-center space-y-4">
          <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3 py-1 text-xs uppercase tracking-[0.18em] text-muted-foreground">
            <ClipboardList className="h-3.5 w-3.5 text-gold-soft" /> Report Catalogue
          </div>
          <h2 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl font-display">
            Tailored Reports for Every <span className="text-gold-gradient">Role & Department</span>
          </h2>
          <p className="text-muted-foreground text-base">
            From CTOs to Lead Engineers, AIAN delivers custom-formatted intelligence straight to your inbox or Slack.
          </p>
        </div>

        <div className="mt-16 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {reportCategories.map((item, i) => {
            const Icon = item.icon;
            return (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className="group relative flex flex-col justify-between rounded-3xl border border-white/10 bg-white/[0.02] p-7 transition-all duration-300 hover:border-gold-soft/40 hover:bg-white/[0.04]"
              >
                <div>
                  <div className="flex items-center justify-between">
                    <div className="rounded-2xl border border-white/10 bg-white/[0.05] p-3 text-gold-soft">
                      <Icon className="h-6 w-6" />
                    </div>
                    <span className="text-[11px] font-mono text-muted-foreground bg-white/[0.04] px-2.5 py-1 rounded-full border border-white/5">
                      {item.freq}
                    </span>
                  </div>
                  <h3 className="mt-5 text-xl font-semibold text-foreground font-display">
                    {item.title}
                  </h3>
                  <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
                    {item.desc}
                  </p>
                </div>

                <div className="mt-6 pt-4 border-t border-white/5 flex items-center justify-between text-xs text-gold-soft font-medium">
                  <span>Auto-Generated by AIAN</span>
                  <span>View Template &rarr;</span>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
